# Add to configs/datasets.yaml

PECANSTREET:
  dishwasher1:
    app: !!str dishwasher1
    house_with_app_i: [661, 1642, 2335, 2361, 2818, 3039, 3456, 3538, 4373, 5746, 7536, 7719, 7800, 7901, 7951, 8156, 8386, 8565, 9160, 9278]
  air1:
    app: !!str air1
    house_with_app_i: [661, 1642, 2335, 2361, 2818, 3039, 3456, 3538, 4373, 5746, 7536, 7719, 7800, 7901, 7951, 8156, 8386, 8565, 9160, 9278]
  clotheswasher1:
    app: !!str clotheswasher1
    house_with_app_i: [661, 1642, 2335, 2361, 2818, 3039, 3456, 3538, 4373, 5746, 7536, 7719, 7800, 7901, 7951, 8156, 8386, 8565, 9160, 9278]
  refrigerator1:
    app: !!str refrigerator1
    house_with_app_i: [661, 1642, 2335, 2361, 2818, 3039, 3456, 3538, 4373, 5746, 7536, 7719, 7800, 7901, 7951, 8156, 8386, 8565, 9160, 9278]
  microwave1:
    app: !!str microwave1
    house_with_app_i: [661, 1642, 2335, 2361, 2818, 3039, 3456, 3538, 4373, 5746, 7536, 7719, 7800, 7901, 7951, 8156, 8386, 8565, 9160, 9278]
